### ISSUE TITLE
Signing raw transaction support

### ISSUE THREAD

**Issue by joeykrug** [LedgerHQ/ledger-wallet-ethereum-chrome#1]
Would be cool if a) the wallet could sign raw ethereum transactions if i say pasted one in and also b) if the wallet supported something like https://github.com/LedgerHQ/ledger-wallet-api but for ethereum.  

That'd be great as then we could use ledger wallet for things like reporting and trading on Augur!

**Comment by btchip** [comment]
We can easily do a), but chose not to do it to display more information for specific contracts. This could be changed, but we'd rather have more details than not enough whenever possible - so if you can point me to the contracts you use (other than ERC-20) I can have a look.

Regarding b) we'll be on it.

**Comment by EricLarch** [comment]
I'm adding this feature on our [roadmap](https://trello.com/c/9AfOTIqc), and we'll do all follow up/comments there.

**Comment by EricLarch** [comment]
Regarding the support of specific contracts we also have a discussion on this feature [here](https://trello.com/c/QGrndIZm).
