### ISSUE TITLE
ENS support

### ISSUE THREAD

**Issue by Arachnid** [LedgerHQ/ledger-wallet-ethereum-chrome#10]
It'd be awesome if the ledger plugin supported ENS! Please feel free to use me as a resource; implementer docs are here: http://docs.ens.domains/en/latest/implementers.html

**Comment by 3X3Q** [comment]
I second this. ENS support would drastically reduce human error when inputting a transaction recipient. This is especially so when sending to friends who might be updating their wallet addresses.

**Comment by ivan-prodanov** [comment]
Any estimation on this? ENS is getting really popular now that they opened 3-6 character domain names. I think it would be really helpful to be able to send transactions to ENS domain names and it’d be nice to see account balance addresses in ENS

**Comment by gre** [comment]
@ivan-prodanov https://github.com/LedgerHQ/ledger-live-desktop is the repository you are looking for. No ETA at the moment.
