### ISSUE TITLE
PLEASE HELP - Final PIN Attempt and only 12 word phrase

### ISSUE THREAD

**Issue by sbassett89** [LedgerHQ/ledger-wallet-ethereum-chrome#17]
I'm in a pickle! I only got a 12 word seed phrase and have 1 attempt left on my pin. I know it's 1 of 2 - but if I get it wrong, I lose all my coins when the wallet is whipped.

Do you think Ledger support could help?

I know:
The address to where all the coins are stored (BTC, ETH and LTC), 12 word seed, access to my Coinbase account where I sent the coins from. And I know it is 1 of 2 pin options?

Any suggestions on what to do? Does the wrong PIN attempts expire after a period of time so I can try out the 2 remaining pin options?

PLEASE HELP

**Comment by btchip** [comment]
Please contact support@ledgerwallet.com - they probably won't be able to help but Github is not a support forum
