### ISSUE TITLE
Ethereum API

### ISSUE THREAD

**Issue by fonzarely** [LedgerHQ/ledger-wallet-ethereum-chrome#2]
I there an API we can use like the web3 object provided by Metamask or Mist ?
I would love to use my Nano S with my apps.
Thanks !

**Comment by btchip** [comment]
We'll have a JS API soon - for the time being you can directly use the application commands documented in https://github.com/LedgerHQ/blue-app-eth/tree/master/doc - there are a few Python samples at https://github.com/LedgerHQ/blue-app-eth

You can subscribe to our developer Slack at http://slack.ledger.co to be notified when it's out and discuss the API features.
