### ISSUE TITLE
Duplicate transactions listed in the wallet (v1.1.0)

### ISSUE THREAD

**Issue by giacecco** [LedgerHQ/ledger-wallet-ethereum-chrome#3]
See the screenshot below. It should show just two transactions coming in, one for 2 eth and one for 1 eth, but both are duplicated. The balance is correct. The logs are [here](https://gist.github.com/giacecco/64465e76e2e057692514400855045258).

![ledger-nano-bug](https://cloud.githubusercontent.com/assets/303693/20184967/47821dc2-a762-11e6-8bcc-1a1109d12430.png)

Thanks.

**Comment by giacecco** [comment]
Just to let you know that I've tried simply restarting the application and there were no duplicates. If you feel you know what happened there, feel free to close this issue. Thanks.

**Comment by Morveus** [comment]
Hi,

Looks like you synced the app during a backend migration (that lasted for a few minutes). The issue should be solved right now since the migration is over and our new servers are up and running.
