### ISSUE TITLE
Upgrading the app: will I lose the wallet?

### ISSUE THREAD

**Issue by giacecco** [LedgerHQ/ledger-wallet-ethereum-chrome#4]
Your website [here](http://support.ledgerwallet.com/knowledge_base/topics/firmware-upgrade-and-application-manager) describes that it is necessary to reinstall the applications and the data from scratch after upgrading the Ledger device firmware. But what happens when upgrading the individual applications? Will I lose the wallets and need to recreate them from the "recovery words" or not? Thanks.

**Comment by pollastri-pierre** [comment]
You don't need to restore your wallet if you just reinstall an application. Remove/installing application doesn't wipe the device, only the firmware update does.
