### ISSUE TITLE
Connect fails when browser support is enabled

### ISSUE THREAD

**Issue by jschornick** [LedgerHQ/ledger-wallet-ethereum-chrome#6]
After testing MyEtherWallet integration using the new "browser support" option in the Ledger Ethereum app, I was no longer able to connect using the Chrome extension. The extension simply hangs at the opening screen "To begin, connect and unlock your Ledger Wallet. Then, open the Ethereum app on your device."

Connecting and reconnecting the device has no effect. Closing and reopening Chrome had no effect. The only way to resolve the issue was to disable "browser support" in the settings. The extension then connects immediately.

Device: Leger Nano S
Firmware: Secure Element 1.2 / MCU 1.0
Ledger App: Ethereum 1.1.0
OS: Ubuntu Linux 16.04
Browser: Chrome 55 / Chromium 53
Extension: Ledger Wallet Ethereum 1.1.0

**Comment by pollastri-pierre** [comment]
Thanks for the report, it's a known issue. For the moment you can only use your wallet on browsers when you use browser support. We will probably add  something to tell the user to disable browser in order to use the chrome application.
